-- =============================================================================
-- PI App — Phase 0 Core Tables
-- Run in: Catalyst Console → Data Store → Run Query (or catalyst datastore:execute)
-- Aligned with Karnataka Police FIR system schema (architecture.md §0)
-- =============================================================================

-- NOTE: Catalyst Data Store uses MySQL syntax. ROWID is auto-generated by Catalyst
--       and should NOT be declared manually. All tables get ROWID automatically.
--       Use CREATORID / CREATEDTIME / MODIFIEDTIME system columns — they exist
--       on every Catalyst table automatically.

-- -----------------------------------------------------------------------------
-- 1. State → District → Unit (police station) hierarchy
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS State (
    ROWID           BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    state_code      VARCHAR(10)    NOT NULL UNIQUE,
    state_name      VARCHAR(100)   NOT NULL,
    CREATEDTIME     DATETIME       DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDTIME    DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS District (
    ROWID           BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    district_code   VARCHAR(20)    NOT NULL UNIQUE,
    district_name   VARCHAR(100)   NOT NULL,
    state_id        BIGINT         NOT NULL,
    CREATEDTIME     DATETIME       DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDTIME    DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (state_id) REFERENCES State(ROWID)
);

-- Unit = Police Station (self-referencing for subdivision hierarchy)
CREATE TABLE IF NOT EXISTS Station (
    ROWID           BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    unit_code       VARCHAR(30)     NOT NULL UNIQUE,
    unit_name       VARCHAR(150)    NOT NULL,
    unit_type       VARCHAR(50)     NOT NULL DEFAULT 'POLICE_STATION',
    district_id     BIGINT          NOT NULL,
    parent_unit_id  BIGINT          NULL,           -- self-ref: sub-division → district HQ
    address         VARCHAR(300)    NULL,
    latitude        DECIMAL(10,7)   NULL,
    longitude       DECIMAL(10,7)   NULL,
    phone           VARCHAR(20)     NULL,
    CREATEDTIME     DATETIME        DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDTIME    DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (district_id)    REFERENCES District(ROWID),
    FOREIGN KEY (parent_unit_id) REFERENCES Station(ROWID)
);

-- -----------------------------------------------------------------------------
-- 2. Rank / Designation lookup (small, stable)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS Rank (
    ROWID           BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    rank_code       VARCHAR(20)    NOT NULL UNIQUE,
    rank_name       VARCHAR(100)   NOT NULL,
    rank_order      INT            NOT NULL DEFAULT 0,   -- lower = senior
    CREATEDTIME     DATETIME       DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDTIME    DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Designation (
    ROWID           BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    designation_code VARCHAR(20)   NOT NULL UNIQUE,
    designation_name VARCHAR(100)  NOT NULL,
    CREATEDTIME     DATETIME       DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDTIME    DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- 3. Officer (Employee in the original schema)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS Officer (
    ROWID              BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    badge_number       VARCHAR(30)    NOT NULL UNIQUE,
    full_name          VARCHAR(150)   NOT NULL,
    rank_id            BIGINT         NULL,
    designation_id     BIGINT         NULL,
    station_id         BIGINT         NOT NULL,
    district_id        BIGINT         NULL,
    -- Catalyst Auth user mapping
    catalyst_user_id   VARCHAR(100)   NULL UNIQUE,   -- maps to Catalyst Auth ROWID
    catalyst_user_email VARCHAR(200)  NULL,
    is_active          TINYINT(1)     NOT NULL DEFAULT 1,
    CREATEDTIME        DATETIME       DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDTIME       DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (rank_id)       REFERENCES Rank(ROWID),
    FOREIGN KEY (designation_id) REFERENCES Designation(ROWID),
    FOREIGN KEY (station_id)    REFERENCES Station(ROWID),
    FOREIGN KEY (district_id)   REFERENCES District(ROWID)
);

-- -----------------------------------------------------------------------------
-- 4. Court
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS Court (
    ROWID           BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    court_name      VARCHAR(200)   NOT NULL,
    court_code      VARCHAR(30)    NULL UNIQUE,
    district_id     BIGINT         NULL,
    CREATEDTIME     DATETIME       DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDTIME    DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (district_id) REFERENCES District(ROWID)
);

-- -----------------------------------------------------------------------------
-- 5. FIR — CaseMaster (hub of the schema)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS FIR (
    ROWID               BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    -- Case identification
    crime_number        VARCHAR(50)     NOT NULL,               -- e.g. "CR-001/2024"
    year                YEAR            NOT NULL,
    station_id          BIGINT          NOT NULL,
    -- Dates
    fir_date            DATETIME        NOT NULL,               -- date FIR was registered
    occurrence_from     DATETIME        NULL,                   -- Inv_OccuranceTime.from
    occurrence_to       DATETIME        NULL,                   -- Inv_OccuranceTime.to
    -- Location of offence
    occurrence_address  VARCHAR(500)    NULL,
    occurrence_lat      DECIMAL(10,7)   NULL,
    occurrence_lng      DECIMAL(10,7)   NULL,
    -- Classification FKs (resolved by lookup tables)
    category_id         BIGINT          NULL,
    gravity_id          BIGINT          NULL,
    crime_head_id       BIGINT          NULL,
    crime_sub_head_id   BIGINT          NULL,
    status_id           BIGINT          NULL,
    court_id            BIGINT          NULL,
    -- Investigating officer
    io_officer_id       BIGINT          NULL,
    -- Brief facts
    brief_facts         TEXT            NULL,                   -- narrative summary
    -- Chargesheet
    chargesheet_filed   TINYINT(1)      NOT NULL DEFAULT 0,
    chargesheet_date    DATETIME        NULL,
    -- Unique constraint: one crime number per station per year
    UNIQUE KEY uq_fir (crime_number, station_id, year),
    CREATEDTIME         DATETIME        DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDTIME        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (station_id)       REFERENCES Station(ROWID),
    FOREIGN KEY (io_officer_id)    REFERENCES Officer(ROWID),
    FOREIGN KEY (court_id)         REFERENCES Court(ROWID)
    -- category_id, gravity_id, crime_head_id, crime_sub_head_id, status_id FKs added
    -- after lookup tables are created (see schema/03_lookup_tables.sql ADD CONSTRAINT section)
);

-- -----------------------------------------------------------------------------
-- 6. Accused
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS Accused (
    ROWID               BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    -- Per-case label (A1, A2 ... — NOT a stable person ID across cases)
    person_label        VARCHAR(10)     NULL,                   -- e.g. "A1"
    -- Personal details
    full_name           VARCHAR(200)    NOT NULL,
    alias               VARCHAR(200)    NULL,
    age                 INT             NULL,
    gender              ENUM('M','F','OTHER','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    father_name         VARCHAR(200)    NULL,
    address             VARCHAR(500)    NULL,
    district_id         BIGINT          NULL,
    state_id            BIGINT          NULL,
    nationality         VARCHAR(100)    NULL DEFAULT 'Indian',
    -- Identity documents (store masked/hashed — raw PII)
    aadhar_hash         VARCHAR(64)     NULL,                   -- SHA-256 of Aadhar; never store plain
    -- Occupation / socioeconomic (sensitive — see architecture.md §4a)
    occupation_id       BIGINT          NULL,
    caste_id            BIGINT          NULL,                   -- SENSITIVE — see §4a
    religion_id         BIGINT          NULL,                   -- SENSITIVE — see §4a
    -- Offender metadata
    is_repeat_offender  TINYINT(1)      NOT NULL DEFAULT 0,
    prior_cases_count   INT             NOT NULL DEFAULT 0,
    -- Resolved person ID (Phase 3 entity resolution — null until Phase 3)
    resolved_person_id  BIGINT          NULL,
    CREATEDTIME         DATETIME        DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDTIME        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (district_id)   REFERENCES District(ROWID),
    FOREIGN KEY (state_id)      REFERENCES State(ROWID)
);

-- -----------------------------------------------------------------------------
-- 7. Victim
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS Victim (
    ROWID               BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    person_label        VARCHAR(10)     NULL,                   -- V1, V2 ...
    full_name           VARCHAR(200)    NOT NULL,
    age                 INT             NULL,
    gender              ENUM('M','F','OTHER','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    father_name         VARCHAR(200)    NULL,
    address             VARCHAR(500)    NULL,
    district_id         BIGINT          NULL,
    phone               VARCHAR(20)     NULL,
    occupation_id       BIGINT          NULL,
    caste_id            BIGINT          NULL,                   -- SENSITIVE
    religion_id         BIGINT          NULL,                   -- SENSITIVE
    injury_description  TEXT            NULL,
    CREATEDTIME         DATETIME        DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDTIME        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (district_id) REFERENCES District(ROWID)
);

-- -----------------------------------------------------------------------------
-- 8. ComplainantDetails (separate from Victim — one FIR has one complainant)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ComplainantDetails (
    ROWID               BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fir_id              BIGINT          NOT NULL UNIQUE,        -- 1:1 with FIR
    full_name           VARCHAR(200)    NOT NULL,
    age                 INT             NULL,
    gender              ENUM('M','F','OTHER','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
    father_name         VARCHAR(200)    NULL,
    address             VARCHAR(500)    NULL,
    phone               VARCHAR(20)     NULL,
    occupation_id       BIGINT          NULL,
    caste_id            BIGINT          NULL,                   -- SENSITIVE — see §4a
    religion_id         BIGINT          NULL,                   -- SENSITIVE — see §4a
    CREATEDTIME         DATETIME        DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDTIME        DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (fir_id) REFERENCES FIR(ROWID)
);
